name: Update YouTube JSON (Python)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install feedparser
        run: pip install feedparser

      - name: Run fetch script
        run: python youtube_fetch.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/youtube.json
          git commit -m "📺 update: latest YouTube RSS (Python)" || echo "No changes to commit"
          git push
