name: Update YouTube JSON (Python)

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write # Changed to write to allow pushing
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install feedparser
        run: pip install feedparser

      - name: Run fetch script
        run: python youtube-fetch.py

      - name: Commit and Push to GitHub
        env:
          # IMPORTANT: Store your Personal Access Token as a repository secret named GH_PAT
          # This token needs 'repo' scope to push commits.
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/services/youtube/card.json
          git commit -m "📺 update: latest YouTube RSS (Python)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main
